// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SuperMarket.FiscalService.Infra.Contexts;
using System;

namespace SuperMarket.FiscalService.Infra.Migrations
{
    [DbContext(typeof(FiscalContext))]
    partial class FiscalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperMarket.FiscalService.Domain.Entities.TaxMoviment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Percentage");

                    b.Property<decimal>("PurchaseOrderBaseValue")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("PurchaseOrderDiscount")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<Guid>("PurchaseOrderId");

                    b.Property<decimal>("PurchaseOrderTotalValue")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrderTaxMoviments");
                });
#pragma warning restore 612, 618
        }
    }
}
